matrix:
  include:
  - os: osx
    osx_image: xcode10.2
    language: node_js
    node_js: '10'
    env:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - os: linux
    services: docker
    language: generic
cache:
  directories:
  - node_modules
  - "$HOME/.cache/electron"
  - "$HOME/.cache/electron-builder"
script:
- |
  if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    docker run --rm \
      --env GH_TOKEN=${GH_TOKEN} \
      -v ${PWD}:/project \
      -v ~/.cache/electron:/root/.cache/electron \
      -v ~/.cache/electron-builder:/root/.cache/electron-builder \
      electronuserland/builder:wine \
      /bin/bash -c "npm install && npm run dist:win"
  else
    npm run dist:mac
  fi
before_cache:
- rm -rf $HOME/.cache/electron-builder/wine
branches:
  only:
  - master
  - "/^v\\d+\\.\\d+\\.\\d+$/"
before_deploy:
- git config --local user.name "phuwasit"
- git config --local user.email "phuwasit@gmail.com"
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
- git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: vbjVpHHWyIJDNRSr22JGi+tYFZdWUCiKlNXWWpJtV+XGZL48fQRCPjj2ARap9xHCyEwSFzCru9KyLzspOmFNW++J2Xfv0csG1Ju1W1QB3yxvMHMtuevk6ias2aOQ6QPYohu6V2WdYSgAccHgSs4NbW3xqtrT5a7ha+LzUcpGE159omK+xhcZ2CiKmbz5sQyrA1cKCuWA4NNFnlJSG52gMypbCnE55WK/i4gQ5BXuhPUrdEB2S9I8NceMOWSuOtlYR8E24x9rrExEzdUgbDkhkfNsqgu5h3ChyozJrAsjLefeRQSRdGE3JBK/apGheLvMOXd79orx+fwLRZgIyvh0ZR5QNwidyPL5FJHKBy17LzxjZ0Aw3JO/imfn0HfnRms6IDobO/QKlkb2+zqv/RiotlIykLlulBN63BI2mDVbd9RpKOICfXnCU/UtnW5jcYyvy+fRFApRzKOpd7KqIb8iKMmX7wo6qMI8fWnJpqUv3uYhu5nt0BtsWaHaFBUXmphaGEbXKMPAILytzestzWGa8tj7NQDqYpQLg/kQgG58L5oMR5Hgh8MCe+RDfpysTHQHNyAqIOFvmoqh57xMdaj7V63zVURmvYHr1u1NWfoavOVrDrRn0sd3Skn1QyQJcSplOMMTbIa3NpHiOV2n/mBcyT7pIffXO5K3Hci0RU2pW44=
  file_glob: true
  file: 
    - "dist/*.{yml,dmg,exe,blockmap}"
    - "latest-mac.yml"
  skip_cleanup: true
  on:
    repo: phuwasit/electron-svelte
    